### PR TITLE
Fixed a bug...

### PR DESCRIPTION
**Pull request by zacwolfe**
Fixed a bug caused by some old code introduced during experimentation, sorry about that!

### CODE REVIEW

**Comment by akshathjain** [comment]
@zacwolfe Can you describe the bug that you fixed?

**Comment by zacwolfe** [comment]
Oops, of course! The bug was forcing the floating panel height to be fixed to the widget's max height, having the side-effect of causing it to be always visible (even when hidden) in the case where the sliding panel was nested in a Stack (rather than employed as the root in a scaffold).

**Comment by zacwolfe** [comment]
Hi there, any update on releasing the slide-direction change? I'm maintaining my own version with the latest release and it's working great but would love to incorporate the official version :)

**Comment by akshathjain** [comment]
Don't worry, I haven't forgotten about this. I'm a little busy, but hopefully I'll add this feature in by the end of the week :)

**Comment by zacwolfe** [comment]
No worries, thank you!

**Comment by akshathjain** [comment]
Everything looks good!

**Comment by akshathjain** [comment]
@zacwolfe  FYI, `slideDirection` has now been incorporated into the v0.3.4 release :)

**Comment by zacwolfe** [comment]
Hi Akshathjain, would it be possible to be added to the contributors for the project? Most repos I've contributed to give credit to all contributors. I'm trying to build up my github to prepare for the wave of Flutter positions I'm certain is coming :). Thanks!

**Pull request merged**
