### PR TITLE
Fix crashing at controller methods

### PR DESCRIPTION
**Pull request by bullet-tooth**
Fix issue #14.

**Issue:** 
Invoking any controller methods before the panel init causes crashing.
It makes it no possible to use [BlocBuilder](https://pub.dev/packages/flutter_bloc#bloc-widgets) for building the panel.

**Crashing exception:**
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building BlocBuilder<PanelBloc, PanelState>(dirty, state: _BlocBuilderBaseState<PanelBloc, PanelState>#1d022):
The method 'call' was called on null.
Receiver: null
Tried calling: call()

User-created ancestor of the error-causing widget was: 
  PanelExample file:///Users/oleg.bondar/my/flutter/my/lib/main2.dart:17:56
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      PanelController.hide (package:sliding_up_panel/src/panel.dart:508:5)
#2      _State.build.<anonymous closure> (package:my/main2.dart:37:17)
#3      BlocBuilder.build (package:flutter_bloc/src/bloc_builder.dart:88:50)
#4      _BlocBuilderBaseState.build (package:flutter_bloc/src/bloc_builder.dart:157:48)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Code example:**
```dart
import 'package:bloc/bloc.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';

void main() {
  runApp(PanelApp());
}

class PanelApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: "PanelApp",
        home: Scaffold(
          body: BlocProvider<PanelBloc>(
              create: (context) => PanelBloc(), child: PanelExample()),
        ));
  }
}

class PanelExample extends StatefulWidget {
  @override
  State createState() {
    return _State();
  }
}

class _State extends State<PanelExample> {
  PanelController _pc = PanelController();

  @override
  Widget build(BuildContext context) => BlocBuilder<PanelBloc, PanelState>(
        builder: (context, state) {
          var text = "";
          if (state is NoDataForPanel) {
            _pc.hide();
          }
          if (state is WithDataForPanel) {
            _pc.show();
            text = state.data;
          }

          return SlidingUpPanel(
            body: Container(
              child: Center(
                child: RaisedButton(onPressed: () {
                  // Click to show panel
                  BlocProvider.of<PanelBloc>(context).add(ShowPanel());
                }),
              ),
            ),
            panel: Text(text),
            controller: _pc,
          );
        },
      );
}

// Bloc
class PanelBloc extends Bloc<PanelEvent, PanelState> {
  @override
  PanelState get initialState => NoDataForPanel();

  @override
  Stream<PanelState> mapEventToState(PanelEvent event) async* {
    if (event is ShowPanel) {
      yield WithDataForPanel("Data to show in panel");
    }
  }
}

// Events
abstract class PanelEvent {}

class ShowPanel extends PanelEvent {}

// States
abstract class PanelState {}

class NoDataForPanel extends PanelState {}

class WithDataForPanel extends PanelState {
  final String data;

  WithDataForPanel(this.data);
}

```

**Additional dependencies:**
[Bloc](https://pub.dev/packages/bloc)
[Flutter bloc](https://pub.dev/packages/flutter_bloc)

### CODE REVIEW

**Comment by digitalkaoz** [comment]
im having a similar problem:

```dart
class Example extends StatelessWidget {
  final PanelController sheet = PanelController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SlidingUpPanel(
        controller: sheet,
        panel: Column(
          children: <Widget>[
            RaisedButton(
              child: Text("Toggle"),
              onPressed: () {
                 //wont work here 
                sheet.isPanelOpen()
                    ? sheet.close()
                    : sheet.open(); 
              },
            ),
            Container(color: Colors.red, height: 500),
          ],
        ),
        body: Container(color: Colors.blue, height: 500),
      ),
    );
  }
}
```

when i attach the debugger inside the panel code, i can clearly see that the listeners are attached, but somehow are lost in the button callback...

**Comment by bullet-tooth** [comment]
@digitalkaoz have you tried to pick up my branch?

**Comment by digitalkaoz** [comment]
@bullet-tooth i didnt, but afaik this would simply do nothing then. so i guess its not the complete fix

**Comment by bullet-tooth** [comment]
> @bullet-tooth i didnt, but afaik this would simply do nothing then. so i guess its not the complete fix

@digitalkaoz what do you think it would suppose to do instead of "do nothing"?

**Comment by digitalkaoz** [comment]
Btw i got the Controller when pulling it into a Provider and have a single instance.

**Comment by bierbaumtim** [comment]
@bullet-tooth It is not recommended to call methods on the controller in BlocBuilder if it depends on the state. Use BlocListener to call methods on the controller. It is more a workaround than a fix. Your _state should look like this:

``` dart
class _State extends State<PanelExample> {
  PanelController _pc = PanelController();

  @override
  Widget build(BuildContext context) => BlocListener<PanelBloc, PanelState>( 
      listener: (context, state) {
        if (state is NoDataForPanel) {
          _pc.hide();
        }
        if (state is WithDataForPanel) {
          _pc.show();
        }
      },
      child: BlocBuilder<PanelBloc, PanelState>(
        builder: (context, state) {
          var text = "";
          if (state is WithDataForPanel) {
            text = state.data;
          }

          return SlidingUpPanel(
            body: Container(
              child: Center(
                child: RaisedButton(onPressed: () {
                  // Click to show panel
                  BlocProvider.of<PanelBloc>(context).add(ShowPanel());
                }),
              ),
            ),
            panel: Text(text),
            controller: _pc,
          );
        },
      );
}
```

**Comment by bullet-tooth** [comment]
@bierbaumtim  thank you for your reply.
>  It is not recommended to call methods on the controller in BlocBuilder if it depends on the state.
Could you please explain why? 

_PR offtopic:_
Actually I would achieve the following logic in my app is to show the panel when a user clicks on an object(there can be many objects on the screen). So as I understand there can be 2 ways to go:
- create new pannel in Stack each time an object clicked
- Mutate the panel state  each time an object clicked (show/hide + rewrite data on the panel)
Could you recommend which way would be better?

**Comment by akshathjain** [comment]
Will merge into a development branch for the panel controller to test.

**Comment by akshathjain** [comment]
@bullet-tooth I found that while this solved the issue, having PanelController methods return null wasn't the clearest behavior. I've instead added an `isAttached` property that returns whether the `PanelController` methods can be safely called, as well as several assert statements that more clearly indicate what the issue is.

**Pull request merged**
